# -*- coding: utf-8 -*-
"""PandasPratica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O7dBu_fgnl45guY74hhR7rNObO6RRdND

# Pratica com Pandas
"""

import pandas as pd
import numpy as np

# =========================
# 1. Criando DataFrame
# =========================
dados = {
    "nome": ["Ana", "Bruno", "Carlos", "Daniela", "Eduardo"],
    "idade": [23, 35, 29, np.nan, 40],
    "cidade": ["SP", "RJ", "SP", "MG", "RJ"],
    "salario": [3000, 5000, 4000, 3500, np.nan],
    "data_contratacao": pd.to_datetime([
        "2020-01-10", "2019-03-15", "2021-07-22", "2018-11-30", "2022-05-10"
    ])
}

# Definindo conjunto de dados como DataFrame
df = pd.DataFrame(dados)
print("DataFrame inicial:\n", df)

# =========================
# 2. Salvando e lendo CSV
# =========================
df.to_csv("dados.csv", index=False)
df = pd.read_csv("dados.csv")

# =========================
# 3. Informações gerais
# =========================
print("\nInfo:")
print(df.info()) # Descubro se é dataframe ou se é series

print("\nEstatísticas:")
print(df.describe())

# =========================
# 4. Tratamento de dados
# =========================
df["idade"] = df["idade"].fillna(df["idade"].mean())
df["salario"] = df["salario"].fillna(df["salario"].median())

# =========================
# 5. Criação de nova coluna
# =========================
df["salario_anual"] = df["salario"] * 12

# =========================
# 6. Filtragem
# =========================
filtro = df[df["salario"] > 3500]
print("\nSalários maiores que 3500:\n", filtro)

# =========================
# 7. Ordenação
# =========================
df_ordenado = df.sort_values(by="salario", ascending=False)
print("\nOrdenado por salário:\n", df_ordenado)

# =========================
# 8. GroupBy
# =========================
media_por_cidade = df.groupby("cidade")["salario"].mean()
print("\nMédia salarial por cidade:\n", media_por_cidade)

# =========================
# 9. Aplicação de função
# =========================
df["categoria_salario"] = df["salario"].apply(
    lambda x: "Alto" if x > 4500 else "Médio" if x > 3000 else "Baixo"
)

# =========================
# 10. Pivot Table
# =========================
pivot = pd.pivot_table(
    df,
    values="salario",
    index="cidade",
    columns="categoria_salario",
    aggfunc="mean"
)
print("\nPivot table:\n", pivot)

# =========================
# 11. Merge (junção)
# =========================
bonus = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carlos", "Daniela", "Eduardo"],
    "bonus": [500, 1000, 700, 600, 800]
})

df_merge = pd.merge(df, bonus, on="nome")
print("\nDataFrame com bônus:\n", df_merge)

# =========================
# 12. Trabalhando com datas
# =========================
df["ano_contratacao"] = pd.to_datetime(df["data_contratacao"]).dt.year

# =========================
# 13. Exportação final
# =========================
df.to_excel("resultado.xlsx", index=False)

print("\nProcesso concluído!")

"""🧠 O que você aprendeu aqui (na prática)

Esse script cobre praticamente o ciclo completo de análise de dados:

📥 Entrada de dados

🧹 Limpeza

🔍 Exploração

📊 Transformação

🔗 Integração

📤 Saída
"""

